---
language: ruby
dist: xenial
rvm: 2.5.3
sudo: required
cache: bundler
cache: yarn

bundler_args: --jobs=3 --retry=3

services:
  - postgresql

addons:
  chrome: stable
  postgresql: "9.6"

before_install:
  - nvm install 12
  - export TZ=Australia/Sydney
  - gem update --system
  - gem install bundler --version 1.17.3

before_script:
  - bin/setup

script:
  - RAILS_ENV=test bundle exec rspec
