SECRET_KEY_BASE: <%= ENV['SECRET_KEY_BASE'] %>
PUA_CLIENT_ID: xxx
PUA_CLIENT_SECRET: xxx
PROJECT_ID: <%= ENV['PROJECT_ID'] %>
NEW_RELIC_LICENSE_KEY: xxx
development:
  GOOGLE_CLIENT_ID: xxx
  GOOGLE_CLIENT_SECRET: xxx
  FACEBOOK_APP_ID: xxx
  FACEBOOK_APP_SECRET: xxx
production:
  GOOGLE_CLIENT_ID: <%= ENV['GOOGLE_CLIENT_ID'] %>
  GOOGLE_CLIENT_SECRET: <%= ENV['GOOGLE_CLIENT_SECRET'] %>
  FACEBOOK_APP_ID: xxx
  FACEBOOK_APP_SECRET: xxx
